version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
  frontend:
    env_file: ./frontend/.env
    build: 
      context: ./frontend
      args: 
        API_URL:
    ports:
      - 3001:3001