version: "3.8"
services:
  database:
    image: postgres:15.2
    env_file: ./backend/.env
    environment:
      POSTGRES_PASSWORD:

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - ${API_PORT}:3000
    depends_on:
      - database
  frontend:
    env_file: ./frontend/.env
    build: 
      context: ./frontend
      args: 
        API_URL:
    ports:
      - 3001:3001